# Config format schema number
format_version: 4

###################
## Model options
model:
  type: SalsaNext
  nclasses: 20

loss:
  type: SalsaLoss
  num_class: 20
  ignore_label: -1

###################
## Dataset options
dataset:
  type: KittiSemRV
  data_root: data/kitti/dataset/sequences/
  label_mapping: data/kitti/semantic-kitti.yaml
  task: train
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    project: True
    fov_up: 3
    fov_down: -25
    width: 2048
    height: 64
  img_means: #range,x,y,z,signal
    - 12.12
    - 10.88
    - 0.23
    - -1.04
    - 0.21
  img_stds: #range,x,y,z,signal
    - 12.32
    - 11.47
    - 6.91
    - 0.86
    - 0.16

dataloader:
  batch_size: 8
  num_workers: 16

# optimizer
optimizer:
  lr: 0.001
  # type: Adam
  type: AdamW
  weight_decay: 0.0001
  # amsgrad: False

# lr_scheduler
lr_scheduler:
  type: StepLR
  step_size: 40

solver:
  # train mode
  epochs: 40
  save_freq: 4599  # also eval_freq
